# Generated by Django 3.2.7 on 2021-10-02 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='partner',
        ),
        migrations.AddField(
            model_name='delivery',
            name='partner_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='deliveries.partnerroute'),
        ),
    ]
