# Generated by Django 3.2.7 on 2021-10-02 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=8, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Patner',
                'verbose_name_plural': 'Patners',
            },
        ),
        migrations.CreateModel(
            name='PartnerRoute',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_place', models.CharField(max_length=50, verbose_name='start_place')),
                ('finish_place', models.CharField(max_length=50, verbose_name='finish_place')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, verbose_name='status')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deliveries.partner')),
            ],
            options={
                'verbose_name': 'PartnerRoute',
                'verbose_name_plural': 'PartnerRoutes',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=100, verbose_name='sender_name')),
                ('sender_address', models.CharField(max_length=100, verbose_name='sender_address')),
                ('sender_city', models.CharField(max_length=50, verbose_name='sender_city')),
                ('sender_postal_code', models.CharField(max_length=10, verbose_name='sender_postal_code')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='receiver_name')),
                ('receiver_address', models.CharField(max_length=100, verbose_name='receiver_address')),
                ('receiver_city', models.CharField(max_length=50, verbose_name='receiver_city')),
                ('receiver_postal_code', models.CharField(max_length=10, verbose_name='receiver_postal_code')),
                ('freight_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='freight_price')),
                ('expected_delivery_date', models.DateField(verbose_name='expected_delivery_date')),
                ('delivery_date', models.DateField(null=True, verbose_name='delivery_date')),
                ('type', models.CharField(choices=[('QUOTATION', 'QUOTATION'), ('DELIVERY', 'DELIVERY')], default='QUOTATION', max_length=9, verbose_name='type')),
                ('status', models.CharField(choices=[('QUOTATION', 'QUOTATION'), ('IN_TRANSIT', 'IN_TRANSIT'), ('DONE', 'DONE')], default='QUOTATION', max_length=10, verbose_name='status')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='deliveries.partner')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
