# Generated by Django 3.2.7 on 2021-10-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_change_column_name_from_partner_to_partner_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='route',
            name='finish_place',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_place',
        ),
        migrations.DeleteModel(
            name='HistoricalRoute',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
