version: "3"

services:
  legacy-system-postgresql:
    image: postgres:13
    container_name: "legacy-system-postgresql"
    environment:
      POSTGRES_PASSWORD: "legacy-system-postgresql"
      POSTGRES_DB: "legacy_system"
      POSTGRES_USER: "legacy_system"
    ports:
      - "15432:5432"
    volumes:
      - ./data/legacy_system:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  deliveries-api-postgresql:
    image: postgres:13
    container_name: "deliveries-api-postgresql"
    environment:
      POSTGRES_PASSWORD: "deliveries_api_postgresql"
      POSTGRES_DB: "deliveries_api"
      POSTGRES_USER: "deliveries_api"
    ports:
      - "25432:5432"
    volumes:
      - ./data/deliveries_api:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
