apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deliveries-api
  name: deliveries-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveries-api
  template:
    metadata:
      labels:
        app: deliveries-api
    spec:
      containers:
        - image: tcc_deliveries_api:0.0.3
          name: deliveries-api
          ports:
            - containerPort: 8001
              name: deliveries-api
          env:
            - name: POSTGRES_PASSWORD
              value: "deliveries_api_postgresql"
            - name: POSTGRES_DB
              value: "deliveries_api"
            - name: POSTGRES_USER
              value: "deliveries_api"
            - name: POSTGRES_HOST
              value: "postgres-deliveries-api"
            - name: POSTGRES_PORT
              value: "5432"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:19092"
---
kind: Service
apiVersion: v1
metadata:
  name: deliveries-api-service
spec:
  selector:
    app: deliveries-api
  ports:
    - port: 8000
