apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zpl-generate-service
    is_tcc: "true"    
  name: zpl-generate-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zpl-generate-service
  template:
    metadata:
      labels:
        app: zpl-generate-service
    spec:
      containers:
        - image: tcc_zpl_generate_service:0.0.1
          name: zpl-generate-service
          env:
            - name: DELIVERIES_API
              value: "http://deliveries-api-service:8000"
            - name: KAFKA_CONSUMER_GROUP
              value: "delivery_plp_process"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: KAFKA_TOPIC
              value: "delivery_plp_process"
            - name: API_TOKEN
              value: "Token PUC_ZPL_GENERATE_SERVICE"