apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-partner-routes-api-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-partner-routes-api-local-storage
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/k8s/partner_routes_api"
    type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-partner-routes-api
spec:
  selector:
    matchLabels:
      app: postgres-partner-routes-api
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-partner-routes-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "partner_routes_api"
            - name: POSTGRES_USER
              value: "partner_routes_api"
            - name: POSTGRES_PASSWORD
              value: "partner_routes_api_postgresql"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-partner-routes-api-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-partner-routes-api
spec:
  selector:
    app: postgres-partner-routes-api
  ports:
    - port: 5432
  type: ClusterIP
