# Generated by Django 3.2.7 on 2021-09-27 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=100, verbose_name='sender_name')),
                ('sender_address', models.CharField(max_length=100, verbose_name='sender_address')),
                ('sender_city', models.CharField(max_length=50, verbose_name='sender_city')),
                ('sender_postal_code', models.CharField(max_length=10, verbose_name='sender_postal_code')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='receiver_name')),
                ('receiver_address', models.CharField(max_length=100, verbose_name='receiver_address')),
                ('receiver_city', models.CharField(max_length=50, verbose_name='receiver_city')),
                ('receiver_postal_code', models.CharField(max_length=10, verbose_name='receiver_postal_code')),
                ('freight_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='freight_price')),
                ('expected_delivery_date', models.DateField(verbose_name='expected_delivery_date')),
                ('delivery_date', models.DateField(null=True, verbose_name='delivery_date')),
                ('type', models.CharField(choices=[('QUOTATION', 'QUOTATION'), ('DELIVERY', 'DELIVERY')], default='QUOTATION', max_length=9, verbose_name='type')),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'IN_TRANSIT'), ('DONE', 'DONE')], default='IN_TRANSIT', max_length=10, verbose_name='status')),
                ('partner_id', models.UUIDField(null=True)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
