# Generated by Django 3.2.7 on 2021-09-27 23:50

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_creating_deliveries_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='end',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='start',
        ),
        migrations.AddField(
            model_name='delivery',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_entry_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_entry_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
