# Generated by Django 3.2.7 on 2021-10-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_add_unique_to_zpl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='partner_id',
            new_name='partner_route_id',
        ),
        migrations.RenameField(
            model_name='historicaldelivery',
            old_name='partner_id',
            new_name='partner_route_id',
        ),
    ]
