# Generated by Django 3.2.7 on 2021-10-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalroute',
            old_name='partner',
            new_name='partner_id',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='partner',
            new_name='partner_id',
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('start_place', 'finish_place', 'partner_id')},
        ),
    ]
