apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deliveries-api
    is_tcc: "true"
  name: deliveries-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deliveries-api
  template:
    metadata:
      labels:
        app: deliveries-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - image: tcc_deliveries_api:0.0.8
          name: deliveries-api
          ports:
            - containerPort: 8000
              name: deliveries-api
          env:
            - name: POSTGRES_PASSWORD
              value: "deliveries_api_postgresql"
            - name: POSTGRES_DB
              value: "deliveries_api"
            - name: POSTGRES_USER
              value: "deliveries_api"
            - name: POSTGRES_HOST
              value: "postgres-deliveries-api"
            - name: POSTGRES_PORT
              value: "5432"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
---
kind: Service
apiVersion: v1
metadata:
  name: deliveries-api-service
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: deliveries-api
  ports:
    - port: 8000
