apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: partner-routes-api
  name: partner-routes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partner-routes-api
  template:
    metadata:
      labels:
        app: partner-routes-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - image: tccpucbernardogomes.azurecr.io/tcc_partner_routes_api:0.0.5
          # - image: tcc_partner_routes_api:0.0.5
          name: partner-routes-api
          ports:
            - containerPort: 8000
              name: main
          env:
            - name: POSTGRES_PASSWORD
              value: "62f5cffbb09b857b338264317a6c17d15d1798d680b677287c373093d698d21f"
            - name: POSTGRES_DB
              value: "d45t0gveqkrg63"
            - name: POSTGRES_USER
              value: "jesguphlmpwtgi"
            - name: POSTGRES_HOST
              value: "ec2-52-87-123-108.compute-1.amazonaws.com"
            - name: POSTGRES_PORT
              value: "5432"
            # - name: POSTGRES_PASSWORD
            #   value: "partner_routes_api_postgresql"
            # - name: POSTGRES_DB
            #   value: "partner_routes_api"
            # - name: POSTGRES_USER
            #   value: "partner_routes_api"
            # - name: POSTGRES_HOST
            #   value: "postgres-partner-routes-api"
            # - name: POSTGRES_PORT
            #   value: "5432"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
---
kind: Service
apiVersion: v1
metadata:
  name: partner-routes-api-service
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: LoadBalancer
  selector:
    app: partner-routes-api
  ports:
    - port: 8000
